### ISSUE TITLE
Refactor Symbolic & SymbolicData

### ISSUE THREAD

**Issue by echatav** [zkFold/zkfold-base#102]
- [x] Move & modify `DiscreteField` from `Symbolic` to `Basic`
- [x] Create a `Trichotomy` class for discrete fields with a total ordering with law of trichotomy
- [x] Create `Trichotomy` instances for `Zp`
- [ ] Create `Trichotomy` instance for `ArithmeticCircuit`
- [x] Redefine `Symbolic` using `Trichotomy`
- [x] Create a `VectorSpace` class for vector spaces over a field with a `Basis` type
- [ ] Create lots of `VectorSpace` instances and relate to `Representable` functors and generics
- [x] Redefine `SymbolicData` using `VectorSpace`
- [ ] Reimplement all `SymbolicData` instances as `VectorSpace` and associated instances
- [x] Create a `Tensorial` class for multlinear maps of vector spaces with `InputBasis` and `OutputSpace` types
- [ ] Redefine `Arithmetizable` using new `SymbolicData`
- [ ] Reimplement all `Arithmetizable` instances
- [ ] Create comparison classes `Eq` and `Ord` for symbolic data with default Foldable implementations and lots of instances
- [x] Create algebraic classes (`AdditiveSemigroup`, etc) for `SymbolicData`
- [ ] Implement algebraic classes for `Identity`, `UInt n`
- [ ] Implement algebraic classes for `Vector n u`
- [ ] Replace list algorithms in UInt and ByteString with vector algorithms

**Comment by echatav** [comment]
@TurtlePU 
Arithmetization looks like this then:
```
class Arithmetizable a f where
  type InputRep a f :: Type
  type OutputRep a f :: Type
  arithmetize :: f -> (InputRep a f -> ArithmeticCircuit a) -> OutputRep a f -> ArithmeticCircuit a

instance SymbolicData a u => Arithmetizable a (u (ArithmeticCircuit a)) where
  type InputRep a (u (ArithmeticCircuit a)) = Void
  type OutputRep a (u (ArithmeticCircuit a)) = Rep a u
  arithmetize c _ = index c

instance (SymbolicData a x, Arithmetizable a f) => Arithmetizable a (x (ArithmeticCircuit a) -> f) where
  type InputRep a (x (ArithmeticCircuit a) -> f) = Either (Rep a x) (InputRep a f)
  type OutputRep a (x (ArithmeticCircuit a) -> f) = OutputRep a f
  arithmetize f i = arithmetize (f $ tabulate (i . Left)) (i . Right)
```

**Comment by vlasin** [comment]
> @TurtlePU
> 
> > Arithmetization looks like this then:
> 
> ```
> class Arithmetizable a f where
>   type InputRep a f :: Type
>   type OutputRep a f :: Type
>   arithmetize :: f -> (InputRep a f -> ArithmeticCircuit a) -> OutputRep a f -> ArithmeticCircuit a
> 
> instance SymbolicData a u => Arithmetizable a (u (ArithmeticCircuit a)) where
>   type InputRep a (u (ArithmeticCircuit a)) = Void
>   type OutputRep a (u (ArithmeticCircuit a)) = Rep a u
>   arithmetize c _ = index c
> 
> instance (SymbolicData a x, Arithmetizable a f) => Arithmetizable a (x (ArithmeticCircuit a) -> f) where
>   type InputRep a (x (ArithmeticCircuit a) -> f) = Either (Rep a x) (InputRep a f)
>   type OutputRep a (x (ArithmeticCircuit a) -> f) = OutputRep a f
>   arithmetize f i = arithmetize (f $ tabulate (i . Left)) (i . Right)
> ```

Why does `arithmetize` have this signature?

**Comment by TurtlePU** [comment]
@vlasin
`InputRep` is an indexing type for function inputs, `OutputRep` is an indexing type for function outputs
To `arithmetize` a function of type `f`, we need to have prepared inputs in a mapping of type `InputRep a f -> ArithmeticCircuit a` and generate outputs in form of a mapping `OutputRep a f -> ArithmeticCircuit a`

**Comment by vlasin** [comment]
> @vlasin
> `InputRep` is an indexing type for function inputs, `OutputRep` is an indexing type for function outputs
> To `arithmetize` a function of type `f`, we need to have prepared inputs in a mapping of type `InputRep a f -> ArithmeticCircuit a` and generate outputs in form of a mapping `OutputRep a f -> ArithmeticCircuit a`

Got you, makes sense.

**Comment by echatav** [comment]
@TurtlePU here's a variant I got past GHC.

```Haskell
class Arithmetizable a f where
  arithmetize :: f -> (Inputs a f -> ArithmeticCircuit a) -> Outputs a f -> ArithmeticCircuit a

type family Inputs a f where
  Inputs a (x (ArithmeticCircuit a) -> f) =
    Either (Basis (ArithmeticCircuit a) x) (Inputs a f)
  Inputs a (u (ArithmeticCircuit a)) = Void

type family Outputs a f where
  Outputs a (x (ArithmeticCircuit a) -> f) = Outputs a f
  Outputs a (u (ArithmeticCircuit a)) = Basis (ArithmeticCircuit a) u

instance {-# OVERLAPPABLE #-}
  ( SymbolicData (ArithmeticCircuit a) u
  , Basis (ArithmeticCircuit a) u ~ Outputs a (u (ArithmeticCircuit a))
  ) => Arithmetizable a (u (ArithmeticCircuit a)) where
    arithmetize c _ = indexV c

instance {-# OVERLAPPING #-}
  ( SymbolicData (ArithmeticCircuit a) x
  , Arithmetizable a f
  ) => Arithmetizable a (x (ArithmeticCircuit a) -> f) where
    arithmetize f i = arithmetize (f $ tabulateV (i . Left)) (i . Right)
```

**Comment by echatav** [comment]
Which we may as well simplify to

```Haskell
class Arithmetizable a f where
  arithmetize :: f -> (Inputs a f -> a) -> Outputs a f -> a

type family Inputs a f where
  Inputs a (x a -> f) = Either (Basis a x) (Inputs a f)
  Inputs a (u a) = Void

type family Outputs a f where
  Outputs a (x a -> f) = Outputs a f
  Outputs a (u a) = Basis a u

instance {-# OVERLAPPABLE #-}
  ( SymbolicData' a u
  , Basis a u ~ Outputs a (u a)
  ) => Arithmetizable a (u a) where
    arithmetize c _ = indexV c

instance {-# OVERLAPPING #-}
  ( SymbolicData' a x
  , Arithmetizable a f
  ) => Arithmetizable a (x a -> f) where
    arithmetize f i = arithmetize (f $ tabulateV (i . Left)) (i . Right)
```

If we unroll the right hand side type of `arithmetize` we get a multilinear function of vector spaces

```
(Inputs a f -> a) -> Outputs a f -> a
~=~
(SymbolicData v0, .. , SymbolicData vN) => vN a -> ... -> v0 a 
```

**Comment by TurtlePU** [comment]
A proposal to unify `Arithmetizable`, `SymbolicData` and `FieldElementData` back into one class:
```haskell
class SymbolicData c d where
  type Input c d :: Type
  type Layout c d :: Type -> Type

  apply :: d -> Input c d -> c (Layout c d)
  restore :: (Input c d -> c (Layout c d)) -> d

instance SymbolicData c (c f) where
  type Input c (c f) = ()
  type Layout c (c f) = f

  apply x _ = x
  restore f = f ()

instance HApplicative c => SymbolicData c () where
  type Input c () = ()
  type Layout c () = U1

  apply _ _ = hpure U1
  restore _ = ()

instance (HApplicative c, SymbolicData c d, SymbolicData c e, Input d ~ Input e) => SymbolicData c (d, e) where
  type Input c (d, e) = Input c d
  type Layout c (d, e) = Layout c d :*: Layout c e

  apply (d, e) i = hliftA2 (:*:) (apply d i) (apply e i)
  restore f = (restore (hmap (\(x :*: _) -> x) . f), restore (hmap (\(_ :*: y) -> y) . f))

instance SymbolicData c d => SymbolicData c (i -> d) where
  type Input c (i -> d) = (i, Input c d)
  type Layout c (i -> d) = Layout c d

  apply f (i, j) = apply (f i) j
  restore f i = restore (\j -> f (i, j))

compile :: (SymbolicData (AC a) f, SymbolicData (AC a) (Input (AC a) f), Input (AC a) (Input (AC a) f) ~ (),
            SymbolicData (AC a) x, Input (AC a) x ~ (), Layout (AC a) x ~ Layout (AC a) f) => f -> x
```

**Comment by echatav** [comment]
I think `SymbolicData` needs to connect to `VectorSpace`?

```
class (Symbolic a, VectorSpace a (RepV a u)) => SymbolicData a u where
  type RepV a u :: Type -> Type
  toSymbolic :: RepV a u a -> u a
  fromSymbolic :: u a -> RepV a u a
```

**Comment by TurtlePU** [comment]
> I think `SymbolicData` needs to connect to `VectorSpace`?

Not necessarily, but we can surely do so
Btw, I think we can use the standard `Representable` from `profunctors` for our functors because now the datatypes itself contain enough info to propagate information about field size to the underlying functor (the `BaseField` associated type in new `Symbolic` class)

**Comment by TurtlePU** [comment]
Proposed definition of `SymbolicData` after we merge #214:
```haskell
class SymbolicData d where
  type Context d :: (Type -> Type) -> Type
  type Support d :: Type
  type Layout d :: Type -> Type

  pieces :: d -> Support d -> Context d (Layout d)
  restore :: (Support d -> Context d (Layout d)) -> d
```

**Comment by echatav** [comment]
closing, obviated by other developments
