### ISSUE TITLE
Create a wrapper function for Plonk proving protocol and a test vector

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#103]
To create the "Prover Backend" component, we need to wrap `prove` function into a function that expects two bytestrings for the setup and the witness and returns a bytestring for the result (the input and the proof):

`proveAPI :: ByteString -> ByteString -> ByteString`

- [x] `proveAPI`
- [ ] test vector

**Comment by iokasimov** [comment]
@vlasin I think I checked all resources I had, but I didn't get what is exactly a `test vector`? Since we have witness and selector ones.

**Comment by vlasin** [comment]
It's a set of test values for 'plonkAPI'.
