### ISSUE TITLE
Incorporate all necessary types for zkFold Symbolic smart contracts into the `Symbolic` constraint

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#113]
We want a typical zkFold Symbolic smart contract to have the following signature:
`contract :: (Symbolic t, Arithmetic a) => t Tx a -> t Input a -> t Bool a`

Here `t` could be the identity or `ArithmeticCircuit`, and `a` is the chosen finite field.

**Comment by TurtlePU** [comment]
So, after #123, we can view Symbolic datatypes as such:

* While running with `Zp p` as base &mdash; `Vector typeSize (Zp p)`
* While running with arithmetic circuits as base &mdash; `ArithmeticCircuit typeSize (Zp p)`

After replacing natural indexing with containers as is currently done in #121 and generalizing from `Zp p` to generic `Arithmetic a`, we get

* `container a` for pure backend
* `ArithmeticCircuit container a` for AC backend

This motivates introducing the following typeclass:
```haskell
class Arithmetic a => Symbolic a t where
  symbolic ::
    (SymbolicData a f, SymbolicData a g) =>
    (forall i m . MonadBlueprint i a m => f i -> m (g i)) ->
    (f a -> g a) -> t f a -> t g a
```

So the user-end code will look like this:
```haskell
instance Symbolic a t => AdditiveSemigroup (t (UInt n) a)

contract :: Symbolic a t => t Tx a -> t Input a -> t Bool a
```

With additional type synonyms we can get:
```
type (~>) f g = forall a t . Symbolic a t => t f a -> t g a
contract :: Tx ~> Input ~> Bool
```

**Comment by TurtlePU** [comment]
Actually, there is also a useful typeclass hierarchy preceding `Symbolic`:
```haskell
class HFunctor t where
  hmap :: (forall a . f a -> g a) -> t f a -> t g a

class HFunctor t => HApplicative t where
  hpure :: (forall a . f a) -> t f a
  hliftA2 :: (forall a. f a -> g a -> h a) -> t f a -> t g a -> t h a

class Lift t where
  lift :: Functor f => f a -> t f a

class (HApplicative t, Lift t) => Symbolic a t where
  symbolic ::
    (SymbolicData a f, SymbolicData a g) =>
    (forall i m . MonadBlueprint i a m => f i -> m (g i)) ->
    (f a -> g a) -> t f a -> t g a
```

**Comment by TurtlePU** [comment]
@echatav
```haskell
class SFunctor f where
  smap :: Symbolic a t => (t u a -> t v a) -> t (f u) a -> t (f v) a

class SFunctor f => SApplicative f where
  spure :: Symbolic a t => t u a => t (f u) a
  sliftA2 :: Symbolic a t => (t u a -> t v a -> t w a) -> t (f u) a -> t (f v) a -> t (f w) a

class SApplicative f => SMonad f where
  sbind :: Symbolic a t => (t u a -> t (f v) a) -> t (f u) a -> t (f v) a

instance Functor f => SFunctor (f :.:)
instance Applicative f => SApplicative (f :.:)
instance Monad f => SMonad (f :.:)
```

**Comment by echatav** [comment]
#157 Is my proposal for resolving this issue.

**Comment by TurtlePU** [comment]
Migration plan
- [ ] `FFA`
- [ ] `ByteString`
- [ ] `UInt` (after #203 is merged)
- [ ] `FieldElement` + remove algebraic instances of `Interpreter a Par1` & `ArithmeticCircuit a Par1`
- [ ] get rid of `MonadBlueprint` and move functions from `ArithmeticCircuit.Combinators` to relevant places of usage
