### ISSUE TITLE
`Binary` instance of `LittleEndian` type appear to represent Big Endian representation

### ISSUE THREAD

**Issue by sourabhxyz** [zkFold/zkfold-base#130]
For the following instance: 

https://github.com/zkFold/zkfold-base/blob/244fc96b15716b3821cd3b512a18de26c75b8aa8/src/ZkFold/Base/Data/ByteString.hs#L32-L47

If we consider the hexadecimal number, `0x12345678` then looking at `put`, number would be stored as `[0x12, 0x34, 0x56, 0x78]`, but this appear to represent Big Endian format instead as most significant byte appears first in the serialisation 🤔, see attached image from [Wikipedia](https://en.wikipedia.org/wiki/Endianness) and how this same example is represented in Little Endian format by [this](https://www.geeksforgeeks.org/little-and-big-endian-mystery/) article.
![image](https://github.com/zkFold/zkfold-base/assets/29835247/56d60ca4-fa3e-4ac5-bc6a-eb7acad98145)

**Comment by sourabhxyz** [comment]
Following modification is what I had in mind: https://github.com/zkFold/zkfold-base/pull/131.

**Comment by echatav** [comment]
You're right, I flipped it!

**Comment by sourabhxyz** [comment]
Completed by https://github.com/zkFold/zkfold-base/pull/131.
