### ISSUE TITLE
In-circuit elliptic curve cryptography

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#143]
Implement elliptic curve operations in-circuit using finite field operations (FFA)

- [x] Refactor FFA to use range constraints
- [x] Add in-circuit implementation for elliptic curve operations
- [x] Add EC ops circuits to benchmarks

Note that Ed25519 operations can be implemented differently than BLS and Pasta curves operations.

**Comment by vlasin** [comment]
We can now use range constraints for these.

**Comment by TurtlePU** [comment]
The efficient implementation is blocked by #223, working on it first
