### ISSUE TITLE
Proposal: Removing `Sig` with overlapping instances.

### ISSUE THREAD

**Issue by echatav** [zkFold/zkfold-base#157]
`Sig` arises because we might have different, non-unified instance implementations for e.g.

```
instance (KnownNat n, Prime p)
  => MultiplicativeSemigroup (UInt n (Zp p))

instance (KnownNat n, PrimeField a)
  => MultiplicativeSemigroup (UInt n (ArithmeticCircuit i Par1 a))

instance (KnownNat n, PrimeField a)
  => MultiplicativeSemigroup (ArithmeticCircuit i (UInt n) a)
```

We can fix this situation by using overlapping instances like so:

```
instance {-# OVERLAPPABLE #-} (KnownNat n, SymbolicField a)
  => MultiplicativeSemigroup (UInt n a)

instance {-# OVERLAPPING #-} (KnownNat n, Prime p)
  => MultiplicativeSemigroup (UInt n (Zp p))

instance {-# OVERLAPPING #-} (KnownNat n, PrimeField a)
  => MultiplicativeSemigroup (UInt n (ArithmeticCircuit i Par1 a))

instance (KnownNat n, PrimeField a)
  => MultiplicativeSemigroup (ArithmeticCircuit i (UInt n) a)
  
-- optimized single circuit UInt (*)
timesUInt
  :: (KnownNat n, PrimeField a)
  => ArithmeticCircuit (UInt n :*: UInt n :*: i) (UInt n) a
```

`Sig` is no longer needed _if_ we can generalize to `SymbolicField`.
When the field is either `Zp p` or a multi-circuit space, the instance will resolve
to this more specific case. The multi-circuit space sub-instance will wrap
the single-circuit instance with `desolder/solder` which will in turn hit
the optimized single-circuit computation with a `curryV` somewhere.
Rewrite rules can be used to fuse away `solder/desolder` and `uncurryV/curryV` compositions,
so that e.g. `compile (*)` gets rewritten to `timesUInt` (aspirationally).
User code won't need to include `Sig` in the context, only `SymbolicField`.
I conjecture that all the instances we need for `Sig` can be resolved,
that is generalized to `SymbolicField`s.
We could even implement the overlappable instances with `error` methods.

**Comment by echatav** [comment]
For functions that we don't have or want to create a type class for, we can use the `{-# SPECIALISE #-}` pragma. If we are clever about using `{-# SPECIALIZE #-}`, `{-# INLINE #-}` and `{-# REWRITE #-}`, I believe we can accomplish performance and cleanliness.

**Comment by TurtlePU** [comment]
Now that I properly understood the proposed solution, I have a question.
Suppose there is a function `f :: SymbolicField a => UInt n a -> Bool a` which uses the `*` as defined above. Wouldn't the instance resolution always resolve to the first instance? Otherwise it should error out and force the user to defer the instance resolution, hence the `Sig` problem.

**Comment by echatav** [comment]
The instance resolves to the more specific instances (the non-error instances). See [documentation](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/instances.html#instance-overlap)

**Comment by TurtlePU** [comment]
An example I tried to cook up:
```haskell
{-# OPTIONS_GHC -Wno-redundant-constraints #-}

module ZkFold.Symbolic.Data.Example where

import ZkFold.Base.Algebra.Basic.Class
import GHC.TypeLits (KnownNat)
import ZkFold.Base.Algebra.Basic.Field (Zp)
import ZkFold.Symbolic.Compiler (Arithmetic, ArithmeticCircuit)
import GHC.Generics (Par1)
import GHC.IO (unsafePerformIO)
import Data.Functor (($>))
import System.IO (putStrLn)

data Example a = None

instance {-# OVERLAPPABLE #-} FiniteField a => AdditiveSemigroup (Example a) where
  _ + _ = unsafePerformIO (putStrLn "finite field instance" $> None)

instance {-# OVERLAPPING #-} KnownNat p => AdditiveSemigroup (Example (Zp p)) where
  _ + _ = unsafePerformIO (putStrLn "zp field instance" $> None)

instance {-# OVERLAPPING #-} Arithmetic a => AdditiveSemigroup (Example (ArithmeticCircuit a Par1)) where
  _ + _ = unsafePerformIO (putStrLn "arithmetic field instance" $> None)

add :: FiniteField a => Example a
add = None + None
```

This throws the following error on usage of `+` in `add`:

```
• Overlapping instances for AdditiveSemigroup (Example a)
    arising from a use of ‘+’
  Matching instance:
    instance [overlappable] FiniteField a =>
                            AdditiveSemigroup (Example a)
      -- Defined at /home/turtle/zkfold-base/src/ZkFold/Symbolic/Data/Example.hs:16:31
  Potentially matching instances:
    instance [overlapping] KnownNat p =>
                           AdditiveSemigroup (Example (Zp p))
      -- Defined at /home/turtle/zkfold-base/src/ZkFold/Symbolic/Data/Example.hs:19:30
    instance [overlapping] Arithmetic a =>
                           AdditiveSemigroup (Example (ArithmeticCircuit a Par1))
      -- Defined at /home/turtle/zkfold-base/src/ZkFold/Symbolic/Data/Example.hs:22:30
  (The choice depends on the instantiation of ‘a’
   To pick the first instance above, use IncoherentInstances
   when compiling the other instance declarations)
• In the expression: None + None
  In an equation for ‘add’: add = None + None (typecheck -Wdeferred-type-errors)
```

**Comment by TurtlePU** [comment]
Basically the same error because of which we had to introduce `Scale a a` in multiple places: until all variables are instantiated, instance resolution might cause incoherence so GHC tries to be conservative in order to be coherent; thus we have to defer the instance resolution to the caller of a generic function.

**Comment by echatav** [comment]
You can use incoherent instances if you really want that example to compile but it's not a more specific example and does not really illustrate what I'm proposing.

**Comment by TurtlePU** [comment]
It still doesn't compile with incoherent instances, sadly
> does not really illustrate what I'm proposing
What would be an illustrative example?

**Comment by vlasin** [comment]
If I understood @TurtlePU correctly, we could reduce `Sig` to `Symbolic c`, where `c` is the context (a circuit or a structure like `Vector`). I think it may be good enough for now.

**Comment by echatav** [comment]
Proposal doesn't seem to work bc GHC cannot defer the instance resolution.
