### ISSUE TITLE
ZK KYC: data types and a KYC check example in Symbolic

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#239]
Add types related to the ZK KYC application to zkFold Symbolic. See this [document](https://github.com/DefyFinancial/defy-zkfold-cross-border-payment/tree/main/src/11-record-kyc-data-ready-for-zk-operations) for details.

Checklist for this issue:

- [ ] All data types and type aliases/newtypes are implemented in Symbolic
- [ ] All data types have JSON instances
- [ ] Create a function in Symbolic that represents a KYC check (a complex boolean expression that uses multiple data fields of different types).

**Comment by vlasin** [comment]
@vks4git I added an example of using Symbolic in this kind of application as a part of this issue. Hope you don't mind :)

**Comment by TurtlePU** [comment]
> All data types have JSON instances

How are `ToJSON` instances of Symbolic datatypes going to be used, btw?

**Comment by vlasin** [comment]
> > All data types have JSON instances
> 
> How are `ToJSON` instances of Symbolic datatypes going to be used, btw?

Do you mean for circuits? We only need them for the interpreter version.

**Comment by TurtlePU** [comment]
> We only need them for the interpreter version.

Oh, okay, nice!

**Comment by vlasin** [comment]
However, we might want a circuit serialization feature at some point. Also, conversions to/from other popular formats.

**Comment by TurtlePU** [comment]
Then I think we can model this more accurately with the help of #308, like this:
```haskell
fromValueJSON :: (SymbolicValue d, FromJSON (Value d)) => ... 
toValueJSON :: (SymbolicValue d, ToJSON (Value d), Context d ~ c, BaseField c ~ WitnessField c) => ...
```
And derive `FromJSON`/`ToJSON` for Symbolic data which would give us circuit serialization behavior
