### ISSUE TITLE
Symbolic Cardano refactoring

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#240]
- [x] Remove `MiMCHash` class (all SymbolicData must be hashable) and refactor `MiMC.hs`
- [x] Switch from `newtype` to `data`
- [x] Implement in-circuit operations on `Value`
- [x] Convenient conversions between basic types (UInt <> ByteString <> FieldElement)

**Comment by TurtlePU** [comment]
@diS3e, if everything is done here, you can link a PR which closes this issue here so this issue is moved to Closed automatically when PR is merged

**Comment by vlasin** [comment]
Yes, I believe it's done. Closing the issue.
