### ISSUE TITLE
Deeper constant optimization

### ISSUE THREAD

**Issue by TurtlePU** [zkFold/zkfold-base#270]
For now, only "explicit constants" are optimized away -- that is, created with `fromConstant :: a -> var` in `MonadCircuit` and with `embed :: Symbolic c => f (BaseField c) -> c f`. More can be optimized:
- [ ] Calls to `newAssigned` where `witness` is evidently constant (e.g. the result of `fromConstant x * fromConstant y`) (#324)
- [ ] Variables whose constraints force them to be constant (e.g. those `k` for which there is a constraint `k - 1 == 0`) (#355)

**Comment by vlasin** [comment]
It seems, the first item can be solved by modifying the `constraint` function instance for `ArithmeticCircuit`.

**Comment by TurtlePU** [comment]
Not the `constraint`, but the `newAssigned` function, I guess, as `constraint` is not able to change any variable

**Comment by vlasin** [comment]
As for the second item, we could do more if we make a reasonable assumption about the set of polynomial equations that are _admissible constraints_. Specifically, if we assume that any substitution of the form $x \rightarrow a_1 x_1 + a_2 x_2 + b$ does not make a valid constraint invalid, then we could eliminate all equations of the form $ a_1 x_1 + a_2 x_2 + a_3 x_3 + b = 0$.
