### ISSUE TITLE
Fix error in `toPlonkConstraint`

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#309]
`ConstVar one` is used in the spot where we are supposed to have an "impossible variable". I believe it appeared as a result of refactoring. The expression
```Haskell
toPlonkConstraint @Fr @1 $ var (ConstVar one)
```
results in an error. Any other value, except `one` works here.

- [x] Fix the error
- [x] Improve the test

**Comment by hovanja2011** [comment]
Here is an example of a polynomial that does not transform into a Plonk constraint: 
`1∙xSysVar (NewVar "y\ETX^\246\226\195\154S\130M\tL\146y\248\201\162\220 \237n6p\bC\151\186\241\US\136\225\139")∙xSysVar (NewVar "~\180\185\222\SOH!\t\254\155\v\SI\187\&9\227\163|^\168Z\184Q\129\rN\218\SYN\GSp\189\139~^")`
