### ISSUE TITLE
SymbolicData should imply constraints on its associated type families

### ISSUE THREAD

**Issue by echatav** [zkFold/zkfold-base#388]
`SymbolicData x` should imply the following constraints
- [x] `Traversable (Layout x)`
- [x] `Representable (Layout x)`
- [x] `Symbolic (Context x)`
- [x] `Representable (Payload x)`

`SymbolicOutput x` should imply `SymbolicData x` as well as the output constraint:
- [x] `Support x ~ Proxy (Context x)`

**Comment by echatav** [comment]
I'm sure about the first two but should the last three constraints also be implications?

**Comment by TurtlePU** [comment]
`Support x ~ Proxy (Context x)` is not always the case because of `instance SymbolicData (x -> f)`
(And also because otherwise we could remove Support as this would always be constant :p)

**Comment by TurtlePU** [comment]
All the other ones are expected, I'd say, was going to propose this myself c:

**Comment by echatav** [comment]
Let's name this the output implication.
```Haskell
Support x ~ Proxy (Context x)
```
Instead of it being an implication of `SymbolicData` it's part of a subconstraint
```
type SymbolicOutput x = (SymbolicData x, Support x ~ Proxy (Context x))
```
This is part of a chain of constraints
```
SymbolicData x < SymbolicOutput x < SymbolicInput x
```
So let's keep its checkmark with the fulfillment criterion being defining and utilizing the `SymbolicOutput` constraint synonym.

**Comment by TurtlePU** [comment]
Agreed, let's do this
