### ISSUE TITLE
Add `Maybe` to zkFold Symbolic

### ISSUE THREAD

**Issue by vlasin** [zkFold/zkfold-base#73]
For any arithmetizable type `f`, `Maybe f` should also be arithmetizable. The constructor should probably be encoded as an additional variable.

**Comment by echatav** [comment]
Given an arithmetizable types `f` and `g` is `Either f g` arithmetizable?

**Comment by vlasin** [comment]
We can make it arithmetizable. In general, to make an ADT arithmetizable, we need to reserve the maximal number of bits plus the number of bits to encode the choice of a constructor. Then, encode those bits in field elements. Something like that.
